cluster.name: {{ pillar['elastic']['cluster_name'] }} 

network.host: 0.0.0.0

http.port: 9200

# The default list of hosts is ["127.0.0.1", "[::1]"]

#discovery.seed_hosts: [{{ grains['ipv4'][2] }}]
#discovery.type: {{ pillar['elastic']['discovery_type'] }}

#cluster.initial_master_nodes: ["node-1", "node-2"]

xpack.security.enabled: {{ pillar['elastic']['xpack_security'] }}
